# Generated by Django 6.1 on 2026-09-01 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_email_alter_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash on Delivery', 'Cash on Delivery'), ('bKash', 'bKash'), ('Nagad', 'Nagad')], default='Cash on Delivery', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='sender_number',
            field=models.CharField(blank=True, help_text='যে নম্বর থেকে টাকা পাঠানো হয়েছে', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='trx_id',
            field=models.CharField(blank=True, help_text='বিকাশ/নগদ ট্রানজেকশন আইডি', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='full_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
