# Generated by Django 6.1 on 2026-09-10 20:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_size_orderitem_size_product_sizes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='কুপন কোড (যেমন: WELCOME20)', max_length=50, unique=True)),
                ('discount_percentage', models.IntegerField(help_text='ডিসকাউন্টের পরিমাণ শতকরা (%) হিসেবে', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True, help_text='কুপনটি অ্যাক্টিভ রাখতে টিক দিন')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
