# Generated by Django 6.1 on 2026-09-11 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='trx_id',
            field=models.CharField(blank=True, help_text='বিকাশ/ন নগদ ট্রানজেকশন আইডি', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='প্রোডাক্টের অন্যান্য ছবি আপলোড করুন', upload_to='product_gallery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product')),
            ],
        ),
    ]
