# Generated by Django 6.1 on 2026-09-11 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_order_trx_id_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='মেগা ফ্ল্যাশ সেল!', max_length=200)),
                ('description', models.CharField(default='টপ প্রোডাক্টগুলোতে স্পেশাল ডিসকাউন্ট। অফার শেষ হতে বাকি:', max_length=500)),
                ('end_time', models.DateTimeField(help_text='ফ্ল্যাশ সেল কখন শেষ হবে তার তারিখ ও সময় দিন')),
                ('is_active', models.BooleanField(default=False, help_text='টিক দিলে ওয়েবসাইটে ব্যানার শো করবে')),
            ],
        ),
    ]
