# Generated by Django 6.1 on 2026-09-11 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_flashsale'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashsale',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='এই সেলে যে প্রোডাক্টগুলো রাখতে চান তা সিলেক্ট করুন', related_name='flash_sales', to='store.product'),
        ),
    ]
