# Generated by Django 6.1 on 2026-09-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_order_discount_amount_order_shipping_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='frequently_bought_together',
            field=models.ManyToManyField(blank=True, help_text='এই প্রোডাক্টের সাথে কাস্টমাররা আর কী কী কিনতে পারে (যেমন: জার্সির সাথে প্যান্ট)', to='store.product'),
        ),
    ]
