# Generated by Django 6.1 on 2026-09-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_product_frequently_bought_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bundle_discount',
            field=models.IntegerField(default=0, help_text='বান্ডেল হিসেবে কিনলে কত % ছাড় দিতে চান? (যেমন: 10, 15)'),
        ),
    ]
