# Generated by Django 6.1 on 2026-09-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_product_bundle_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, help_text='কাস্টমারের দেওয়া আসল ছবি', null=True, upload_to='review_images/'),
        ),
    ]
