# Generated by Django 6.1 on 2026-09-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_review_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=3000.0, help_text='কত টাকার শপিং করলে ফ্রি ডেলিভারি পাবে?', max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, help_text='কাস্টমারের দেওয়া আসল ছবি', null=True, upload_to='review_images/'),
        ),
    ]
