# Generated by Django 6.1 on 2026-09-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_storesetting_alter_review_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesetting',
            name='is_free_shipping_active',
            field=models.BooleanField(default=True, help_text='ফ্রি শিপিং অফার চালু রাখতে টিক দিন'),
        ),
    ]
