# Generated by Django 6.1 on 2026-09-19 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_storesetting_is_free_shipping_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='storesetting',
            name='abandoned_cart_active',
            field=models.BooleanField(default=True, help_text='কাস্টমার কার্টে পণ্য রেখে চলে গেলে রিকভারি ইমেইল পাঠাতে টিক দিন', verbose_name='অ্যাবানডনড কার্ট রিকভারি চালু রাখুন'),
        ),
        migrations.AddField(
            model_name='storesetting',
            name='abandoned_cart_discount_percent',
            field=models.PositiveIntegerField(default=5, help_text='ইমেইলে কত শতাংশ ডিসকাউন্টের কুপন দেওয়া হবে (০ দিলে ডিসকাউন্ট ছাড়া শুধু রিমাইন্ডার যাবে)', verbose_name='রিকভারি ডিসকাউন্ট (%)'),
        ),
        migrations.AddField(
            model_name='storesetting',
            name='abandoned_cart_email_subject',
            field=models.CharField(default='আপনার কার্টের পছন্দের পণ্যগুলো আপনার জন্য অপেক্ষা করছে!', help_text='কাস্টমার যে সাবজেক্ট লাইনের ইমেইল পাবে', max_length=255, verbose_name='রিকভারি ইমেইল সাবজেক্ট'),
        ),
        migrations.AddField(
            model_name='storesetting',
            name='abandoned_cart_wait_hours',
            field=models.PositiveIntegerField(default=2, help_text='কার্ট রেখে যাওয়ার কত ঘণ্টা পর ইমেইল পাঠাবে (ডিফল্ট: ২ ঘণ্টা)', verbose_name='কত ঘণ্টা পর ইমেইল যাবে'),
        ),
        migrations.CreateModel(
            name='AbandonedCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ইমেইল')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='ফোন')),
                ('cart_data', models.JSONField(default=dict, verbose_name='কার্ট ডাটা')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='মোট মূল্য')),
                ('coupon_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='কুপন কোড')),
                ('discount_percent', models.PositiveIntegerField(default=0, verbose_name='ডিসকাউন্ট %')),
                ('is_email_sent', models.BooleanField(default=False, verbose_name='ইমেইল পাঠানো হয়েছে?')),
                ('email_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='ইমেইল পাঠানোর সময়')),
                ('is_recovered', models.BooleanField(default=False, verbose_name='রিকভার হয়েছে? (অর্ডার সম্পন্ন)')),
                ('recovered_at', models.DateTimeField(blank=True, null=True, verbose_name='রিকভারির সময়')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তৈরির সময়')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='সর্বশেষ আপডেট')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abandoned_carts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Abandoned Cart',
                'verbose_name_plural': 'Abandoned Carts',
                'ordering': ['-updated_at'],
            },
        ),
    ]
